In [1]:
import numpy as np

np.random.seed(42)

A  = np.random.randint(0, 10, size=(3000,300,200))

B  = np.random.randint(0, 10, size=(3000,200,400))

print("A:\n{}, shape={}\nB:\n{}, shape={}".format(A, A.shape,B, B.shape))

A:
[[[6 3 7 ... 3 1 5]
  [5 0 8 ... 5 8 7]
  [4 0 6 ... 8 0 0]
  ...
  [2 5 2 ... 5 8 5]
  [9 0 4 ... 5 5 6]
  [7 0 9 ... 0 1 0]]

 [[8 6 8 ... 6 9 0]
  [5 0 3 ... 5 3 4]
  [9 8 1 ... 6 0 8]
  ...
  [0 7 6 ... 6 9 4]
  [7 3 6 ... 0 3 4]
  [8 4 8 ... 8 0 0]]

 [[4 3 9 ... 9 5 9]
  [4 2 8 ... 7 9 3]
  [8 2 7 ... 9 8 9]
  ...
  [5 4 2 ... 7 4 5]
  [8 6 5 ... 0 8 5]
  [6 8 7 ... 2 6 6]]

 ...

 [[4 1 9 ... 1 6 7]
  [5 2 6 ... 1 6 2]
  [0 0 1 ... 4 4 5]
  ...
  [4 6 0 ... 0 6 6]
  [5 3 5 ... 0 2 3]
  [1 9 4 ... 1 8 3]]

 [[4 2 5 ... 9 2 3]
  [2 8 8 ... 2 0 8]
  [4 1 9 ... 1 6 3]
  ...
  [6 2 7 ... 1 6 8]
  [3 0 6 ... 1 2 8]
  [5 6 4 ... 4 4 0]]

 [[1 6 8 ... 3 7 2]
  [1 3 1 ... 1 1 9]
  [5 7 8 ... 2 8 2]
  ...
  [7 6 3 ... 9 7 6]
  [7 9 7 ... 4 2 1]
  [7 6 0 ... 6 9 4]]], shape=(3000, 300, 200)
B:
[[[3 9 9 ... 3 9 8]
  [1 8 6 ... 6 1 5]
  [0 9 7 ... 6 7 5]
  ...
  [0 7 8 ... 1 3 8]
  [9 1 3 ... 3 4 9]
  [9 3 7 ... 5 5 4]]

 [[9 0 3 ... 4 7 0]
  [8 0 2 ... 9 9 7]
  [0 4 8 ... 6 6 9]
  ...
  